angular.module('contactGrid')
    .factory('contactStorage', function() {
        var STORAGE_ID = 'contactArray';

        return {
            get: function() {
                return JSON.parse(localStorage.getItem(STORAGE_ID)) || [{
                    "active": true,
                    "age": 28,
                    "first_name": "Regina",
                    "last_name": "Mckay",
                    "email": "reginamckay@zboo.com"
                }, {
                    "active": true,
                    "age": 37,
                    "first_name": "Ruthie",
                    "last_name": "Jacobson",
                    "email": "ruthiejacobson@zboo.com"
                }, {
                    "active": true,
                    "age": 34,
                    "first_name": "Small",
                    "last_name": "Chavez",
                    "email": "smallchavez@zboo.com"
                }, {
                    "active": true,
                    "age": 38,
                    "first_name": "Alexander",
                    "last_name": "Evans",
                    "email": "alexanderevans@zboo.com"
                }, {
                    "active": false,
                    "age": 26,
                    "first_name": "Hays",
                    "last_name": "Daniel",
                    "email": "haysdaniel@zboo.com"
                }, {
                    "active": true,
                    "age": 26,
                    "first_name": "Mccormick",
                    "last_name": "Shepherd",
                    "email": "mccormickshepherd@zboo.com"
                }, {
                    "active": true,
                    "age": 38,
                    "first_name": "Weeks",
                    "last_name": "Duffy",
                    "email": "weeksduffy@zboo.com"
                }, {
                    "active": true,
                    "age": 39,
                    "first_name": "Benton",
                    "last_name": "Collier",
                    "email": "bentoncollier@zboo.com"
                }, {
                    "active": false,
                    "age": 34,
                    "first_name": "Desiree",
                    "last_name": "Skinner",
                    "email": "desireeskinner@zboo.com"
                }, {
                    "active": true,
                    "age": 32,
                    "first_name": "Bell",
                    "last_name": "Herring",
                    "email": "bellherring@zboo.com"
                }, {
                    "active": true,
                    "age": 26,
                    "first_name": "Dolores",
                    "last_name": "Spencer",
                    "email": "doloresspencer@zboo.com"
                }, {
                    "active": false,
                    "age": 30,
                    "first_name": "Higgins",
                    "last_name": "Mckenzie",
                    "email": "higginsmckenzie@zboo.com"
                }, {
                    "active": false,
                    "age": 39,
                    "first_name": "Lillian",
                    "last_name": "Wooten",
                    "email": "lillianwooten@zboo.com"
                }, {
                    "active": false,
                    "age": 22,
                    "first_name": "Tabatha",
                    "last_name": "Blackburn",
                    "email": "tabathablackburn@zboo.com"
                }, {
                    "active": true,
                    "age": 34,
                    "first_name": "Castillo",
                    "last_name": "Black",
                    "email": "castilloblack@zboo.com"
                }, {
                    "active": true,
                    "age": 20,
                    "first_name": "Matilda",
                    "last_name": "Hardin",
                    "email": "matildahardin@zboo.com"
                }, {
                    "active": false,
                    "age": 40,
                    "first_name": "Dixon",
                    "last_name": "Dean",
                    "email": "dixondean@zboo.com"
                }, {
                    "active": true,
                    "age": 29,
                    "first_name": "Candy",
                    "last_name": "Green",
                    "email": "candygreen@zboo.com"
                }, {
                    "active": true,
                    "age": 35,
                    "first_name": "Booth",
                    "last_name": "Gilmore",
                    "email": "boothgilmore@zboo.com"
                }, {
                    "active": true,
                    "age": 32,
                    "first_name": "Rosemarie",
                    "last_name": "Mcpherson",
                    "email": "rosemariemcpherson@zboo.com"
                }, {
                    "active": false,
                    "age": 35,
                    "first_name": "Owens",
                    "last_name": "Cleveland",
                    "email": "owenscleveland@zboo.com"
                }, {
                    "active": false,
                    "age": 26,
                    "first_name": "Pacheco",
                    "last_name": "Shields",
                    "email": "pachecoshields@zboo.com"
                }, {
                    "active": true,
                    "age": 35,
                    "first_name": "Ayala",
                    "last_name": "Brewer",
                    "email": "ayalabrewer@zboo.com"
                }, {
                    "active": true,
                    "age": 26,
                    "first_name": "Oneal",
                    "last_name": "Blackwell",
                    "email": "onealblackwell@zboo.com"
                }, {
                    "active": true,
                    "age": 32,
                    "first_name": "Hogan",
                    "last_name": "Patton",
                    "email": "hoganpatton@zboo.com"
                }, {
                    "active": false,
                    "age": 26,
                    "first_name": "Rosanne",
                    "last_name": "Blanchard",
                    "email": "rosanneblanchard@zboo.com"
                }, {
                    "active": true,
                    "age": 30,
                    "first_name": "Curtis",
                    "last_name": "Herman",
                    "email": "curtisherman@zboo.com"
                }, {
                    "active": true,
                    "age": 40,
                    "first_name": "Amalia",
                    "last_name": "Coleman",
                    "email": "amaliacoleman@zboo.com"
                }, {
                    "active": false,
                    "age": 31,
                    "first_name": "Lea",
                    "last_name": "Morgan",
                    "email": "leamorgan@zboo.com"
                }, {
                    "active": false,
                    "age": 29,
                    "first_name": "Bertie",
                    "last_name": "Payne",
                    "email": "bertiepayne@zboo.com"
                }, {
                    "active": false,
                    "age": 20,
                    "first_name": "Rollins",
                    "last_name": "Benton",
                    "email": "rollinsbenton@zboo.com"
                }, {
                    "active": true,
                    "age": 32,
                    "first_name": "Buckley",
                    "last_name": "Cline",
                    "email": "buckleycline@zboo.com"
                }, {
                    "active": true,
                    "age": 21,
                    "first_name": "Gonzalez",
                    "last_name": "Lopez",
                    "email": "gonzalezlopez@zboo.com"
                }];
            },

            put: function(contacts) {
                localStorage.setItem(STORAGE_ID, JSON.stringify(contacts));
            }
        };
    });
